import { Factory, Calendar, Package, Clock } from 'lucide-react';
import Card from '../components/Card.jsx';
import DataTable from '../components/DataTable.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import { LoadingTable, ErrorState } from '../components/Loading.jsx';
import PageHeader from '../components/PageHeader.jsx';
import { useFetch } from '../hooks/useFetch.js';
import { fetchProductionPlans } from '../api/client.js';
import { formatDate, formatNumber } from '../utils/formatters.js';

export default function ProductionPlans() {
  const { data: plans, loading, error, refetch } = useFetch(fetchProductionPlans, []);

  if (loading) return <LoadingTable rows={5} cols={6} />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;

  const items = plans || [];
  const totalOutput = items.reduce((s, p) => s + (p.totalQuantity || 0), 0);
  const pendingPlans = items.filter((p) => p.status === 'PENDING_APPROVAL').length;

  const columns = [
    {
      key: '_id',
      label: 'Plan ID',
      render: (val) => (
        <span className="font-mono text-xs text-surface-500">{val?.slice(-8)}</span>
      ),
    },
    {
      key: 'purchaseOrderId',
      label: 'Purchase Order',
      render: (val) => (
        <span className="font-medium text-primary-600">
          {typeof val === 'object' ? val?.poNumber : val?.slice(-8) || '—'}
        </span>
      ),
    },
    {
      key: 'totalQuantity',
      label: 'Output (Sets)',
      render: (val) => (
        <span className="font-semibold text-surface-800">{formatNumber(val)}</span>
      ),
    },
    {
      key: 'totalProductionDays',
      label: 'Days',
      render: (val) => (
        <span className="text-surface-600">{val} days</span>
      ),
    },
    {
      key: 'plannedStartDate',
      label: 'Start',
      render: (val) => <span className="text-surface-600">{formatDate(val)}</span>,
    },
    {
      key: 'plannedEndDate',
      label: 'End',
      render: (val) => <span className="text-surface-600">{formatDate(val)}</span>,
    },
    {
      key: 'status',
      label: 'Status',
      render: (val) => <StatusBadge status={val} />,
    },
    {
      key: 'generatedBy',
      label: 'Generated By',
      render: (val, row) => (
        <div>
          <span className="text-xs font-medium text-surface-600">{val}</span>
          {row.confidenceScore && (
            <span className="text-xs text-surface-400 ml-1">
              ({(row.confidenceScore * 100).toFixed(0)}%)
            </span>
          )}
        </div>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <PageHeader 
        title="Production Plans"
        description="Monitor and manage manufacturing schedules and outputs"
      />

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card title="Total Plans" value={items.length} icon={Factory} />
        <Card title="Total Output" value={`${formatNumber(totalOutput)} sets`} icon={Package}>
          <p className="text-xs mt-1 text-surface-500">Combined scheduled production</p>
        </Card>
        <Card
          title="Pending Approval"
          value={pendingPlans}
          icon={Clock}
        >
          <p className="text-xs mt-1 text-surface-500">
            {pendingPlans > 0 ? 'Requires manager review' : 'All approved'}
          </p>
        </Card>
        <Card title="Avg. Duration" value={items.length ? `${Math.round(items.reduce((s, p) => s + (p.totalProductionDays || 0), 0) / items.length)} days` : '—'} icon={Calendar} />
      </div>

      {/* Schedule Details for each plan */}
      {items.map((plan) => (
        <div key={plan._id} className="bg-white rounded-xl border border-surface-200 p-6 space-y-4 shadow-sm">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-surface-50 border border-surface-200 flex items-center justify-center">
                <Factory className="w-5 h-5 text-surface-500" />
              </div>
              <div>
                <h3 className="text-sm font-semibold text-surface-900">
                  {typeof plan.purchaseOrderId === 'object'
                    ? plan.purchaseOrderId?.poNumber
                    : `Plan ${plan._id?.slice(-8)}`}
                </h3>
                <p className="text-xs text-surface-500 mt-0.5">
                  {formatDate(plan.plannedStartDate)} → {formatDate(plan.plannedEndDate)} · {plan.totalProductionDays} days
                </p>
              </div>
            </div>
            <StatusBadge status={plan.status} size="md" />
          </div>

          {/* Schedule Table */}
          {plan.schedule && plan.schedule.length > 0 && (
            <div className="overflow-x-auto mt-4">
              <table className="w-full text-sm border border-surface-200 rounded-lg">
                <thead>
                  <tr className="border-b border-surface-200 bg-surface-50">
                    <th className="text-left py-2 px-3 text-xs font-medium text-surface-500 uppercase tracking-wider">Date</th>
                    <th className="text-left py-2 px-3 text-xs font-medium text-surface-500 uppercase tracking-wider">Product</th>
                    <th className="text-right py-2 px-3 text-xs font-medium text-surface-500 uppercase tracking-wider">Quantity</th>
                    <th className="text-left py-2 px-3 text-xs font-medium text-surface-500 uppercase tracking-wider">Shift</th>
                    <th className="text-left py-2 px-3 text-xs font-medium text-surface-500 uppercase tracking-wider">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-surface-100">
                  {plan.schedule.map((s, i) => (
                    <tr key={i} className="hover:bg-surface-50 transition-colors">
                      <td className="py-2.5 px-3 text-surface-800">{formatDate(s.date)}</td>
                      <td className="py-2.5 px-3 font-mono text-xs text-surface-600">{s.productCode}</td>
                      <td className="py-2.5 px-3 text-right font-semibold text-surface-900">{formatNumber(s.plannedQuantity)}</td>
                      <td className="py-2.5 px-3 text-surface-500 text-xs">{s.shift?.replace('_', ' ')}</td>
                      <td className="py-2.5 px-3"><StatusBadge status={s.status} size="xs" /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Assumptions */}
          {plan.assumptions && plan.assumptions.length > 0 && (
            <div className="bg-surface-50 border border-surface-200 rounded-lg p-4 mt-4">
              <p className="text-xs font-semibold text-surface-700 mb-2">Planning Assumptions</p>
              <ul className="text-xs text-surface-600 space-y-1 list-disc list-inside">
                {plan.assumptions.map((a, i) => (
                  <li key={i}>{a}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      ))}

      {/* Fallback if no plans */}
      {items.length === 0 && (
        <div className="text-center py-12 text-surface-400 bg-white rounded-xl border border-surface-200">
          <Factory className="w-12 h-12 mx-auto mb-3 text-surface-300" />
          <p className="font-medium text-surface-600">No production plans generated yet</p>
          <p className="text-sm mt-1">Process a purchase order to generate a production plan</p>
        </div>
      )}
    </div>
  );
}
